version: "1"
services:
  location:
    environment:
      TAG: location
    build: ./location
    container_name: location
    restart: on-failure
    ports:
      - "8082:8082"
    env_file:
      - .env

  profile:
    environment:
      TAG: profile
    build: ./profile
    container_name: profile
    restart: on-failure
    ports:
      - "8083:8083"
    env_file:
      - .env

  vehicle:
    environment:
      TAG: vehicle
    build: ./vehicle
    container_name: vehicle
    restart: on-failure
    ports:
      - "8084:8084"
    env_file:
      - .env

  trip:
    environment:
      TAG: trip
    build: ./trip
    container_name: trip
    restart: on-failure
    ports:
      - "8085:8085"
    env_file:
      - .env

  booking:
    environment:
      TAG: booking
    build: ./booking
    container_name: booking
    restart: on-failure
    ports:
      - "8086:8086"
    env_file:
      - .env