version: "1"
services:
  auth-server:
    environment:
      TAG: AUTH
    build: ./auth-server
    container_name: auth-server
    restart: on-failure
    ports:
      - "9000:9000"
    env_file:
      - .env

  location:
    environment:
      TAG: location
    build: ./location
    container_name: location
    restart: on-failure
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - auth-server

  profile:
    environment:
      TAG: profile
    build: ./profile
    container_name: profile
    restart: on-failure
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      - auth-server

  vehicle:
    environment:
      TAG: vehicle
    build: ./vehicle
    container_name: vehicle
    restart: on-failure
    ports:
      - "8084:8084"
    env_file:
      - .env
    depends_on:
      - auth-server