version: "1"
services:
  location:
    environment:
      TAG: location
      TZ: Asia/Ho_Chi_Minh
    build: ./location
    container_name: location
    restart: on-failure
    ports:
      - "8082:8082"
    env_file:
      - .env

  profile:
    environment:
      TAG: profile
      TZ: Asia/Ho_Chi_Minh
    build: ./profile
    container_name: profile
    restart: on-failure
    ports:
      - "8083:8083"
    env_file:
      - .env

  vehicle:
    environment:
      TAG: vehicle
      TZ: Asia/Ho_Chi_Minh
    build: ./vehicle
    container_name: vehicle
    restart: on-failure
    ports:
      - "8084:8084"
    env_file:
      - .env

  trip:
    environment:
      TAG: trip
      TZ: Asia/Ho_Chi_Minh
    build: ./trip
    container_name: trip
    restart: on-failure
    ports:
      - "8085:8085"
    env_file:
      - .env

  booking:
    environment:
      TAG: booking
      TZ: Asia/Ho_Chi_Minh
    build: ./booking
    container_name: booking
    restart: on-failure
    ports:
      - "8086:8086"
    env_file:
      - .env

  notification:
    environment:
      TAG: notification
      TZ: Asia/Ho_Chi_Minh
    build: ./notification
    container_name: notification
    restart: on-failure
    ports:
      - "8087:8087"
    env_file:
      - .env