server:
  port: 8083

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/profile
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: profile
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URL}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    sentinel:
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: ${BOOTSTRAP1}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
      properties:
        enable:
          idempotence: true
        max:
          in:
            flight:
              request:
                per:
                  connection: 5
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest

logging:
  level:
    org.springframework.cache: trace
    org.ehcache: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

management:
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: ${BASE_URL}/api/v2/spans
  endpoints:
    web:
      exposure:
        include: info, health

url:
  base-url: ${SSL}://${DOMAIN}
  auth-url: ${AUTH_DOMAIN}

springdoc:
  swagger-ui:
    path: /swagger-ui.html