spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  config:
    import: optional:configserver:http://localhost:8081

server:
  port: 8080

eureka:
  client:
    register-with-eureka: false