spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/location
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: false
          dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.43.39:9000

server:
  port: 8082

eureka:
  instance:
    hostname: ${EUREKA_HOST}
    client:
      service-url:
        defaultZone: ${DEFAULT_ZONE_EUREKA}