spring:
  application:
    name: location
  data:
    mongodb:
      uri: mongodb+srv://${LOCATION_DB_USER}:${LOCATION_DB_PASSWORD}@${LOCATION_DB_HOST}/${LOCATION_DB_DBNAME}?retryWrites=true&w=majority&appName=Cluster0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URL}

server:
  port: 8082

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              MongoTemplate.Query: TRACE
client:
  client-id: web-client

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${client.client-id}
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: ${SWAGGER_DOMAIN}/swagger-ui/oauth2-redirect.html

management:
  endpoints:
    web:
      exposure:
        include: info, health

url:
#  base-url: ${SSL}://${DOMAIN}/api/v1
  base-url: http://localhost:8082

geocoding:
  api-key: ${API_KEY}


internal-api-key:
  location: ${LOCATION_API_KEY}

